### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '.'

### ISSUE THREAD

**Issue by 0x00111** [271374667/NuitkaGUI#11]
DEBUG - initVar.py - 56 - 2024-04-18 23:45:30,883 - 日志记录器初始化完成
DEBUG - initVar.py - 154 - 2024-04-18 23:45:30,930 - 当前系统编码为:utf-8
DEBUG - initVar.py - 159 - 2024-04-18 23:45:30,930 - 寻找到一个Python路径:C:\Program Files\Python38\python.exe
DEBUG - initVar.py - 165 - 2024-04-18 23:45:30,930 - 当前Python路径为:C:\Program Files\Python38\python.exe
DEBUG - comment.py - 101 - 2024-04-18 23:45:30,946 - 正在测试源的响应速度...
DEBUG - comment.py - 107 - 2024-04-18 23:45:30,961 - https://pypi.tuna.tsinghua.edu.cn/simple的响应时间为inf秒
DEBUG - comment.py - 107 - 2024-04-18 23:45:31,211 - http://mirrors.aliyun.com/pypi/simple/的响应时间为0.263824秒
DEBUG - comment.py - 107 - 2024-04-18 23:45:31,211 - https://pypi.mirrors.ustc.edu.cn/simple/的响应时间为inf秒
DEBUG - comment.py - 107 - 2024-04-18 23:45:32,092 - http://pypi.douban.com/simple/的响应时间为inf秒
DEBUG - comment.py - 107 - 2024-04-18 23:45:32,262 - http://pypi.mirrors.ustc.edu.cn/simple/的响应时间为1.320968秒
DEBUG - initVar.py - 184 - 2024-04-18 23:45:32,278 - 设置默认pip源为http://mirrors.aliyun.com/pypi/simple/
DEBUG - initVar.py - 68 - 2024-04-18 23:45:32,278 - 正在检查nuitka模块版本...
DEBUG - comment.py - 20 - 2024-04-18 23:45:32,278 - 线程:Thread-4已启动,目标函数为:initModuleVersion,参数为:(),关键字参数为:{}
DEBUG - comment.py - 20 - 2024-04-18 23:45:32,278 - 线程:Thread-5已启动,目标函数为:initWindowArgs,参数为:(),关键字参数为:{}
DEBUG - initVar.py - 179 - 2024-04-18 23:45:32,278 - 初始化页面完成
DEBUG - initVar.py - 188 - 2024-04-18 23:45:32,278 - 正在检查gcc可用性...
DEBUG - initVar.py - 192 - 2024-04-18 23:45:32,278 - gcc不可用
DEBUG - comment.py - 101 - 2024-04-18 23:45:32,278 - 正在测试源的响应速度...
DEBUG - comment.py - 107 - 2024-04-18 23:45:32,293 - https://download.yzuu.cf/skeeto/w64devkit/releases/download/v1.20.0/w64devkit-1.20.0.zip的响应时间为inf秒
DEBUG - comment.py - 148 - 2024-04-18 23:45:32,293 - 正在解压GCC压缩包...
Traceback (most recent call last):
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\start.py", line 28, in <module>
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 47, in initWindow
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 195, in initGcc
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\src\utils\comment.py", line 150, in installGcc
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\src\customWidget\myProgressDialog.py", line 63, in extract
  File "C:\Users\FunkYou\AppData\Local\Temp\ONEFIL~1\zipfile.py", line 1239, in __init__
PermissionError: [Errno 13] Permission denied: '.'
DEBUG - initVar.py - 118 - 2024-04-18 23:45:32,434 - 获取到28个插件
DEBUG - initVar.py - 121 - 2024-04-18 23:45:32,434 - 插件参数初始化完成
DEBUG - initVar.py - 70 - 2024-04-18 23:45:32,699 - nuitka模块版本为2.1.5
DEBUG - initVar.py - 85 - 2024-04-18 23:45:32,699 - 正在检查pipreqs模块版本...
DEBUG - initVar.py - 87 - 2024-04-18 23:45:33,106 - pipreqs模块版本为0.5.0
确实看不懂了 权限也给了但是还是提示

**Comment by 0x00111** [comment]
解决了 管理员cmd，加上代理终端，就能解决上面的问题，GCC正在自己解决，希望出个牛逼的版本，感谢作者
