### ISSUE TITLE
0.06在win10启动失败

### ISSUE THREAD

**Issue by xiaomingtt** [271374667/NuitkaGUI#14]
下载的0.06版本，电脑win10LTSCx64，安装了python3.10x64和python3.8x86.启动程序后几个黑窗闪过，也看不清写的什么。

**Comment by xiaomingtt** [comment]
看到了日志：
DEBUG - initVar.py - 56 - 2024-08-30 09:49:46,657 - 日志记录器初始化完成
DEBUG - initVar.py - 154 - 2024-08-30 09:49:46,756 - 当前系统编码为:utf-8
DEBUG - initVar.py - 159 - 2024-08-30 09:49:46,757 - 寻找到一个Python路径:C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe
DEBUG - initVar.py - 165 - 2024-08-30 09:49:46,796 - 当前Python路径为:C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe
DEBUG - comment.py - 101 - 2024-08-30 09:49:46,810 - 正在测试源的响应速度...
DEBUG - comment.py - 107 - 2024-08-30 09:49:47,054 - https://pypi.tuna.tsinghua.edu.cn/simple的响应时间为0.22759秒
DEBUG - comment.py - 107 - 2024-08-30 09:49:47,103 - http://mirrors.aliyun.com/pypi/simple/的响应时间为0.281536秒
DEBUG - comment.py - 107 - 2024-08-30 09:49:47,200 - https://pypi.mirrors.ustc.edu.cn/simple/的响应时间为0.369387秒
DEBUG - comment.py - 107 - 2024-08-30 09:49:47,201 - http://pypi.douban.com/simple/的响应时间为inf秒
DEBUG - comment.py - 107 - 2024-08-30 09:49:47,202 - http://pypi.mirrors.ustc.edu.cn/simple/的响应时间为0.227572秒
DEBUG - initVar.py - 184 - 2024-08-30 09:49:47,204 - 设置默认pip源为http://pypi.mirrors.ustc.edu.cn/simple/
DEBUG - initVar.py - 68 - 2024-08-30 09:49:47,207 - 正在检查nuitka模块版本...
DEBUG - comment.py - 20 - 2024-08-30 09:49:47,207 - 线程:Thread-4已启动,目标函数为:initModuleVersion,参数为:(),关键字参数为:{}
DEBUG - comment.py - 20 - 2024-08-30 09:49:47,210 - 线程:Thread-5已启动,目标函数为:initWindowArgs,参数为:(),关键字参数为:{}
DEBUG - initVar.py - 179 - 2024-08-30 09:49:47,230 - 初始化页面完成
DEBUG - initVar.py - 188 - 2024-08-30 09:49:47,239 - 正在检查gcc可用性...
DEBUG - initVar.py - 192 - 2024-08-30 09:49:47,241 - gcc不可用
DEBUG - comment.py - 148 - 2024-08-30 09:49:47,244 - 正在解压GCC压缩包...
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\start.py", line 28, in <module>
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 47, in initWindow
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 195, in initGcc
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\utils\comment.py", line 150, in installGcc
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\customWidget\myProgressDialog.py", line 63, in extract
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\zipfile.py", line 1257, in __init__
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\zipfile.py", line 1324, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\threading.py", line 954, in _bootstrap_inner
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\threading.py", line 892, in run
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 129, in initWindowArgs
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\src\core\initVar.py", line 104, in initPlugins
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 420, in check_output
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONEFIL~1\subprocess.py", line 524, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'nuitka', '--plugin-list']' returned non-zero exit status 1.
DEBUG - initVar.py - 70 - 2024-08-30 09:49:48,237 - nuitka模块版本为
INFO - initVar.py - 72 - 2024-08-30 09:49:48,237 - 未检测到nuitka模块,正在自动安装...
INFO - initVar.py - 74 - 2024-08-30 09:49:49,438 - nuitka模块安装完成
DEBUG - initVar.py - 85 - 2024-08-30 09:49:49,438 - 正在检查pipreqs模块版本...
DEBUG - initVar.py - 87 - 2024-08-30 09:49:50,059 - pipreqs模块版本为
INFO - initVar.py - 89 - 2024-08-30 09:49:50,059 - 未检测到pipreqs模块,正在自动安装...
INFO - initVar.py - 91 - 2024-08-30 09:49:50,955 - pipreqs模块安装完成

**Comment by xiaomingtt** [comment]
弄好gcc在主环境装好nuitka、pipreqs就好了。
